local addon = _G.DragonUI_Addon
local H = addon.OptionsHelpers or {}
local set = H.createSetFunction or function() return function() end end

local function BuildUnitFramesOptions()
    return {
        type='group', name='Unit Frames', order=5, childGroups='tree', args={
            general = { type='group', name='General', inline=true, order=1, args={
                scale = { type='range', order=1, name='Global Scale', desc='Global scale for all unit frames', min=0.5, max=2.0, step=0.1,
                    get=function() return addon.db.profile.unitframe.scale end,
                    set=set('unitframe','scale',nil,'RefreshUnitFrames') },
            }},

            player = { type='group', name='Player Frame', order=2, args={
                scale = { type='range', order=1, name='Scale', desc='Scale of the player frame', min=0.5, max=2.0, step=0.1,
                    get=function() return addon.db.profile.unitframe.player.scale end,
                    set=set('unitframe','player','scale','RefreshUnitFrames') },
                classcolor = { type='toggle', order=2, name='Class Color', desc='Use class color for health bar',
                    get=function() return addon.db.profile.unitframe.player.classcolor end,
                    set=set('unitframe','player','classcolor','RefreshUnitFrames') },
                breakUpLargeNumbers = { type='toggle', order=3, name='Large Numbers', desc='Format large numbers (1k, 1m)',
                    get=function() return addon.db.profile.unitframe.player.breakUpLargeNumbers end,
                    set=set('unitframe','player','breakUpLargeNumbers','RefreshUnitFrames') },
                textFormat = { type='select', order=4, name='Text Format', desc='How to display health and mana values', values={ numeric='Current Value Only', percentage='Percentage Only', both='Both (Numbers + Percentage)', formatted='Current/Max Values' },
                    get=function() return addon.db.profile.unitframe.player.textFormat end,
                    set=set('unitframe','player','textFormat','RefreshUnitFrames') },
                showHealthTextAlways = { type='toggle', order=5, name='Always Show Health Text', desc='Show health text always (true) or only on hover (false)',
                    get=function() return addon.db.profile.unitframe.player.showHealthTextAlways end,
                    set=set('unitframe','player','showHealthTextAlways','RefreshUnitFrames') },
                showManaTextAlways = { type='toggle', order=6, name='Always Show Mana Text', desc='Show mana/power text always (true) or only on hover (false)',
                    get=function() return addon.db.profile.unitframe.player.showManaTextAlways end,
                    set=set('unitframe','player','showManaTextAlways','RefreshUnitFrames') },
                override = { type='toggle', order=6, name='Override Position', desc='Override default positioning',
                    get=function() return addon.db.profile.unitframe.player.override end,
                    set=set('unitframe','player','override','RefreshUnitFrames') },
                x = { type='range', order=7, name='X Position', desc='Horizontal position', min=-1000, max=1000, step=1,
                    get=function() return addon.db.profile.unitframe.player.x end,
                    set=set('unitframe','player','x','RefreshUnitFrames'), disabled=function() return not addon.db.profile.unitframe.player.override end },
                y = { type='range', order=8, name='Y Position', desc='Vertical position', min=-1000, max=1000, step=1,
                    get=function() return addon.db.profile.unitframe.player.y end,
                    set=set('unitframe','player','y','RefreshUnitFrames'), disabled=function() return not addon.db.profile.unitframe.player.override end },
            }},

            target = { type='group', name='Target Frame', order=3, args={
                scale = { type='range', order=1, name='Scale', desc='Scale of the target frame', min=0.5, max=2.0, step=0.1,
                    get=function() return addon.db.profile.unitframe.target.scale end,
                    set=set('unitframe','target','scale','RefreshUnitFrames') },
                classcolor = { type='toggle', order=2, name='Class Color', desc='Use class color for health bar',
                    get=function() return addon.db.profile.unitframe.target.classcolor end,
                    set=set('unitframe','target','classcolor','RefreshUnitFrames') },
                breakUpLargeNumbers = { type='toggle', order=3, name='Large Numbers', desc='Format large numbers (1k, 1m)',
                    get=function() return addon.db.profile.unitframe.target.breakUpLargeNumbers end,
                    set=set('unitframe','target','breakUpLargeNumbers','RefreshUnitFrames') },
                textFormat = { type='select', order=4, name='Text Format', desc='How to display health and mana values', values={ numeric='Current Value Only', percentage='Percentage Only', both='Both (Numbers + Percentage)', formatted='Current/Max Values' },
                    get=function() return addon.db.profile.unitframe.target.textFormat end,
                    set=set('unitframe','target','textFormat','RefreshUnitFrames') },
                showHealthTextAlways = { type='toggle', order=5, name='Always Show Health Text', desc='Show health text always (true) or only on hover (false)',
                    get=function() return addon.db.profile.unitframe.target.showHealthTextAlways end,
                    set=set('unitframe','target','showHealthTextAlways','RefreshUnitFrames') },
                showManaTextAlways = { type='toggle', order=6, name='Always Show Mana Text', desc='Show mana/power text always (true) or only on hover (false)',
                    get=function() return addon.db.profile.unitframe.target.showManaTextAlways end,
                    set=set('unitframe','target','showManaTextAlways','RefreshUnitFrames') },
                enableThreatGlow = { type='toggle', order=6, name='Threat Glow', desc='Show threat glow effect',
                    get=function() return addon.db.profile.unitframe.target.enableThreatGlow end,
                    set=set('unitframe','target','enableThreatGlow','RefreshUnitFrames') },
                override = { type='toggle', order=7, name='Override Position', desc='Override default positioning',
                    get=function() return addon.db.profile.unitframe.target.override end,
                    set=set('unitframe','target','override','RefreshUnitFrames') },
                x = { type='range', order=8, name='X Position', desc='Horizontal position', min=-1000, max=1000, step=1,
                    get=function() return addon.db.profile.unitframe.target.x end,
                    set=set('unitframe','target','x','RefreshUnitFrames'), disabled=function() return not addon.db.profile.unitframe.target.override end },
                y = { type='range', order=10, name='Y Position', desc='Vertical position', min=-1000, max=1000, step=1,
                    get=function() return addon.db.profile.unitframe.target.y end,
                    set=set('unitframe','target','y','RefreshUnitFrames'), disabled=function() return not addon.db.profile.unitframe.target.override end },
            }},

            tot = { type='group', name='Target of Target', order=4, args={
                scale = { type='range', order=1, name='Scale', desc='Scale of the target of target frame', min=0.5, max=2.0, step=0.1,
                    get=function() return addon.db.profile.unitframe.tot.scale end,
                    set=set('unitframe','tot','scale','RefreshUnitFrames') },
                classcolor = { type='toggle', order=2, name='Class Color', desc='Use class color for health bar',
                    get=function() return addon.db.profile.unitframe.tot.classcolor end,
                    set=set('unitframe','tot','classcolor','RefreshUnitFrames') },
                x = { type='range', order=3, name='X Position', desc='Horizontal position offset', min=-200, max=200, step=1,
                    get=function() return addon.db.profile.unitframe.tot.x end,
                    set=set('unitframe','tot','x','RefreshUnitFrames') },
                y = { type='range', order=4, name='Y Position', desc='Vertical position offset', min=-200, max=200, step=1,
                    get=function() return addon.db.profile.unitframe.tot.y end,
                    set=set('unitframe','tot','y','RefreshUnitFrames') },
            }},

            fot = { type='group', name='Target of Focus', order=4.5, args={
                scale = { type='range', order=1, name='Scale', desc='Scale of the focus of target frame', min=0.5, max=2.0, step=0.1,
                    get=function() return addon.db.profile.unitframe.fot.scale end,
                    set=set('unitframe','fot','scale','RefreshUnitFrames') },
                classcolor = { type='toggle', order=2, name='Class Color', desc='Use class color for health bar',
                    get=function() return addon.db.profile.unitframe.fot.classcolor end,
                    set=set('unitframe','fot','classcolor','RefreshUnitFrames') },
                x = { type='range', order=3, name='X Position', desc='Horizontal position offset', min=-200, max=200, step=1,
                    get=function() return addon.db.profile.unitframe.fot.x end,
                    set=set('unitframe','fot','x','RefreshUnitFrames') },
                y = { type='range', order=4, name='Y Position', desc='Vertical position offset', min=-200, max=200, step=1,
                    get=function() return addon.db.profile.unitframe.fot.y end,
                    set=set('unitframe','fot','y','RefreshUnitFrames') },
            }},

            focus = { type='group', name='Focus Frame', order=5, args={
                scale = { type='range', order=1, name='Scale', desc='Scale of the focus frame', min=0.5, max=2.0, step=0.1,
                    get=function() return addon.db.profile.unitframe.focus.scale end,
                    set=set('unitframe','focus','scale','RefreshUnitFrames') },
                classcolor = { type='toggle', order=2, name='Class Color', desc='Use class color for health bar',
                    get=function() return addon.db.profile.unitframe.focus.classcolor end,
                    set=set('unitframe','focus','classcolor','RefreshUnitFrames') },
                breakUpLargeNumbers = { type='toggle', order=3, name='Large Numbers', desc='Format large numbers (1k, 1m)',
                    get=function() return addon.db.profile.unitframe.focus.breakUpLargeNumbers end,
                    set=set('unitframe','focus','breakUpLargeNumbers','RefreshUnitFrames') },
                textFormat = { type='select', order=4, name='Text Format', desc='How to display health and mana values', values={ numeric='Current Value Only', percentage='Percentage Only', both='Both (Numbers + Percentage)', formatted='Current/Max Values' },
                    get=function() return addon.db.profile.unitframe.focus.textFormat end,
                    set=set('unitframe','focus','textFormat','RefreshUnitFrames') },
                showHealthTextAlways = { type='toggle', order=5, name='Always Show Health Text', desc='Show health text always (true) or only on hover (false)',
                    get=function() return addon.db.profile.unitframe.focus.showHealthTextAlways end,
                    set=set('unitframe','focus','showHealthTextAlways','RefreshUnitFrames') },
                showManaTextAlways = { type='toggle', order=6, name='Always Show Mana Text', desc='Show mana/power text always (true) or only on hover (false)',
                    get=function() return addon.db.profile.unitframe.focus.showManaTextAlways end,
                    set=set('unitframe','focus','showManaTextAlways','RefreshUnitFrames') },
                override = { type='toggle', order=6, name='Override Position', desc='Override default positioning',
                    get=function() return addon.db.profile.unitframe.focus.override end,
                    set=set('unitframe','focus','override','RefreshUnitFrames') },
                x = { type='range', order=7, name='X Position', desc='Horizontal position', min=-1000, max=1000, step=1,
                    get=function() return addon.db.profile.unitframe.focus.x end,
                    set=set('unitframe','focus','x','RefreshUnitFrames'), disabled=function() return not addon.db.profile.unitframe.focus.override end },
                y = { type='range', order=8, name='Y Position', desc='Vertical position', min=-1000, max=1000, step=1,
                    get=function() return addon.db.profile.unitframe.focus.y end,
                    set=set('unitframe','focus','y','RefreshUnitFrames'), disabled=function() return not addon.db.profile.unitframe.focus.override end },
            }},

            pet = { type='group', name='Pet Frame', order=6, args={
                scale = { type='range', order=1, name='Scale', desc='Scale of the pet frame', min=0.5, max=2.0, step=0.1,
                    get=function() return addon.db.profile.unitframe.pet.scale end,
                    set=set('unitframe','pet','scale','RefreshPetFrame') },
                textFormat = { type='select', order=2, name='Text Format', desc='How to display health and mana values', values={ numeric='Current Value Only', percentage='Percentage Only', both='Both (Numbers + Percentage)', formatted='Current/Max Values' },
                    get=function() return addon.db.profile.unitframe.pet.textFormat end,
                    set=set('unitframe','pet','textFormat','RefreshPetFrame') },
                breakUpLargeNumbers = { type='toggle', order=3, name='Large Numbers', desc='Format large numbers (1k, 1m)',
                    get=function() return addon.db.profile.unitframe.pet.breakUpLargeNumbers end,
                    set=set('unitframe','pet','breakUpLargeNumbers','RefreshPetFrame') },
                showHealthTextAlways = { type='toggle', order=4, name='Always Show Health Text', desc='Always display health text (otherwise only on mouseover)',
                    get=function() return addon.db.profile.unitframe.pet.showHealthTextAlways end,
                    set=set('unitframe','pet','showHealthTextAlways','RefreshPetFrame') },
                showManaTextAlways = { type='toggle', order=5, name='Always Show Mana Text', desc='Always display mana/energy/rage text (otherwise only on mouseover)',
                    get=function() return addon.db.profile.unitframe.pet.showManaTextAlways end,
                    set=set('unitframe','pet','showManaTextAlways','RefreshPetFrame') },
                enableThreatGlow = { type='toggle', order=6, name='Threat Glow', desc='Show threat glow effect',
                    get=function() return addon.db.profile.unitframe.pet.enableThreatGlow end,
                    set=set('unitframe','pet','enableThreatGlow','RefreshPetFrame') },
                override = { type='toggle', order=7, name='Override Position', desc='Allows the pet frame to be moved freely. When unchecked, it will be positioned relative to the player frame.',
                    get=function() return addon.db.profile.unitframe.pet.override end,
                    set=set('unitframe','pet','override','RefreshPetFrame') },
                x = { type='range', order=10, name='X Position', desc='Horizontal position (only active if Override is checked)', min=-2500, max=2500, step=1,
                    get=function() return addon.db.profile.unitframe.pet.x end,
                    set=set('unitframe','pet','x','RefreshPetFrame'), disabled=function() return not addon.db.profile.unitframe.pet.override end },
                y = { type='range', order=11, name='Y Position', desc='Vertical position (only active if Override is checked)', min=-2500, max=2500, step=1,
                    get=function() return addon.db.profile.unitframe.pet.y end,
                    set=set('unitframe','pet','y','RefreshPetFrame'), disabled=function() return not addon.db.profile.unitframe.pet.override end },
            }},

            party = { type='group', name='Party Frames', order=7, args={
                scale = { type='range', order=1, name='Scale', desc='Scale of party frames', min=0.5, max=2.0, step=0.1,
                    get=function() return addon.db.profile.unitframe.party.scale end,
                    set=set('unitframe','party','scale','RefreshUnitFrames') },
                classcolor = { type='toggle', order=2, name='Class Color', desc='Use class color for health bars',
                    get=function() return addon.db.profile.unitframe.party.classcolor end,
                    set=set('unitframe','party','classcolor','RefreshUnitFrames') },
                textFormat = { type='select', order=3, name='Text Format', desc='How to display health and mana values', values={ numeric='Current Value Only', percentage='Percentage Only', both='Both (Numbers + Percentage)', formatted='Current/Max Values' },
                    get=function() return addon.db.profile.unitframe.party.textFormat end,
                    set=set('unitframe','party','textFormat','RefreshUnitFrames') },
                breakUpLargeNumbers = { type='toggle', order=4, name='Large Numbers', desc='Format large numbers (1k, 1m)',
                    get=function() return addon.db.profile.unitframe.party.breakUpLargeNumbers end,
                    set=set('unitframe','party','breakUpLargeNumbers','RefreshUnitFrames') },
                showHealthTextAlways = { type='toggle', order=5, name='Always Show Health Text', desc='Always display health text (otherwise only on mouseover)',
                    get=function() return addon.db.profile.unitframe.party.showHealthTextAlways end,
                    set=set('unitframe','party','showHealthTextAlways','RefreshUnitFrames') },
                showManaTextAlways = { type='toggle', order=6, name='Always Show Mana Text', desc='Always display mana/energy/rage text (otherwise only on mouseover)',
                    get=function() return addon.db.profile.unitframe.party.showManaTextAlways end,
                    set=set('unitframe','party','showManaTextAlways','RefreshUnitFrames') },
                orientation = { type='select', order=7, name='Orientation', desc='Party frame orientation', values={ vertical='Vertical', horizontal='Horizontal' },
                    get=function() return addon.db.profile.unitframe.party.orientation end,
                    set=set('unitframe','party','orientation','RefreshUnitFrames') },
                padding = { type='range', order=8, name='Padding', desc='Space between party frames', min=0, max=50, step=1,
                    get=function() return addon.db.profile.unitframe.party.padding end,
                    set=set('unitframe','party','padding','RefreshUnitFrames') },
                override = { type='toggle', order=10, name='Override Position', desc='Override default party frame position',
                    get=function() return addon.db.profile.unitframe.party.override end,
                    set=set('unitframe','party','override','RefreshUnitFrames') },
                x = { type='range', order=10, name='X Position', desc='Horizontal position', min=-1000, max=1000, step=1,
                    get=function() return addon.db.profile.unitframe.party.x end,
                    set=set('unitframe','party','x','RefreshUnitFrames'), disabled=function() return not addon.db.profile.unitframe.party.override end },
                y = { type='range', order=11, name='Y Position', desc='Vertical position', min=-1000, max=1000, step=1,
                    get=function() return addon.db.profile.unitframe.party.y end,
                    set=set('unitframe','party','y','RefreshUnitFrames'), disabled=function() return not addon.db.profile.unitframe.party.override end },
            }},
        }
    }
end

addon:RegisterOptionsSection('unitframe', 5, BuildUnitFramesOptions)

